Repository Cumulus-Cloud/cumulus, pull requests merged in 2018-04, with the labels that each got.

#124 Chunk deletion on file deletion
  server/app/CumulusLoader.scala
  server/app/io/cumulus/controllers/FileSystemController.scala
  server/app/io/cumulus/core/stream/storage/StorageReferenceReader.scala
  server/app/io/cumulus/persistence/services/FsNodeService.scala
  server/app/io/cumulus/persistence/services/StorageService.scala
  server/app/io/cumulus/persistence/storage/ChunkRemover.scala
  server/app/io/cumulus/persistence/storage/StorageEngine.scala
Labels: back, need review

#123 New upload
  client/README.md
  client/package-lock.json
  client/package.json
  client/src/components/FsNodeComponent.css
  client/src/components/FsNodeComponent.tsx
  client/src/components/buttons/BaseButton.css
  client/src/components/buttons/BaseButton.tsx
  client/src/components/buttons/GhostButton.css
  client/src/components/buttons/IconButton.css
  client/src/components/buttons/IconButton.tsx
  client/src/components/modals/ModalActions.css
  client/src/components/progress/ProgressBar.tsx
  client/src/components/progress/ProgressBlock.css
  client/src/components/progress/ProgressBlock.tsx
  client/src/components/upload/UploadFile.css
  client/src/components/upload/UploadFile.tsx
  client/src/components/upload/Uploader.css
  client/src/components/upload/Uploader.tsx
  client/src/files/fileSystem/FileSystemContainer.tsx
  client/src/files/rename/FsNodeName.css
  client/src/files/upload/DropUploader.tsx
  client/src/files/upload/DropUploaderContainer.tsx
  client/src/files/upload/ReducedUploader.css
  client/src/files/upload/ReducedUploader.tsx
  client/src/files/upload/UploadActions.ts
  client/src/files/upload/UploadContainer.tsx
  client/src/files/upload/UploadModal.css
  client/src/files/upload/UploadModal.tsx
  client/src/files/upload/UploadReducer.ts
  client/src/icons/ArrowUpIcon.tsx
  client/src/icons/CompressIcon.tsx
  client/src/icons/LockCloseIcon.tsx
  client/src/icons/LockOpenIcon.tsx
  client/src/icons/UploadIcon.tsx
  client/src/main.tsx
  client/src/models/FileToUpload.ts
  client/src/models/UploadModalStatus.ts
  client/src/store.ts
  client/src/utils/files.ts
  client/src/utils/querystring.ts
  server/conf/messages.conf
  server/conf/messages.fr.conf
Labels: front, need review

#127 Allow download of an empty file
  server/app/io/cumulus/core/stream/storage/StorageReferenceReader.scala
Labels: back, fix

#128 New font
  client/src/components/upload/UploadFile.css
  client/src/main.css
  server/app/io/cumulus/views/index.scala.html
Labels: enhancement, front

#129 fix create directory request
  client/package-lock.json
  client/package.json
  client/src/files/newFolder/NewFolderEpics.ts
  client/src/services/Api.ts
Labels: bug, front

#130 Pagination and sorting for files
  server/app/io/cumulus/controllers/FileSystemController.scala
  server/app/io/cumulus/core/persistence/anorm/AnormPKOperations.scala
  server/app/io/cumulus/core/persistence/query/QueryFilter.scala
  server/app/io/cumulus/core/persistence/query/QueryOrdering.scala
  server/app/io/cumulus/core/persistence/query/QueryPagination.scala
  server/app/io/cumulus/persistence/services/FsNodeService.scala
  server/app/io/cumulus/persistence/stores/FsNodeStore.scala
  server/app/io/cumulus/persistence/stores/filters/FsNodeFilter.scala
  server/app/io/cumulus/persistence/stores/orderings/FsNodeOrdering.scala
  server/conf/routes
  server/test/FileSystemSpec.scala
Labels: back, need review

#136 Use parcel.js instead webpack
  client/.postcssrc
  client/package-lock.json
  client/package.json
  client/src/auth/AuthLayout.css
  client/src/auth/bg.jpg
  client/webpack.config.js
  server/.gitignore
Labels: enhancement, front

#142 New sharing API
  server/app/CumulusLoader.scala
  server/app/io/cumulus/controllers/FileSystemController.scala
  server/app/io/cumulus/controllers/SharingController.scala
  server/app/io/cumulus/controllers/SharingManagementController.scala
  server/app/io/cumulus/persistence/services/SharingService.scala
  server/conf/routes
Labels: back, need review

#154 Sharing api update
  server/app/io/cumulus/controllers/FileSystemController.scala
  server/app/io/cumulus/controllers/SharingController.scala
  server/app/io/cumulus/controllers/SharingManagementController.scala
  server/app/io/cumulus/core/Settings.scala
  server/app/io/cumulus/core/controllers/utils/api/ApiUtils.scala
  server/app/io/cumulus/core/persistence/anorm/AnormPKOperations.scala
  server/app/io/cumulus/core/persistence/query/QueryPagination.scala
  server/app/io/cumulus/core/utils/PaginatedList.scala
  server/app/io/cumulus/models/SharingInfo.scala
  server/app/io/cumulus/models/fs/FsNode.scala
  server/app/io/cumulus/persistence/services/FsNodeService.scala
  server/app/io/cumulus/persistence/services/SharingService.scala
  server/app/io/cumulus/persistence/stores/FsNodeStore.scala
  server/app/io/cumulus/persistence/stores/SharingStore.scala
  server/conf/application.conf
  server/conf/routes
Labels: back, enhancement, need review

#167 Fix route prefix
  server/src/main/scala/io/cumulus/CumulusServer.scala
Labels: back, fix, need review

#171 Fix sharing queries
  server/src/main/scala/io/cumulus/persistence/stores/SharingStore.scala
Labels: back, fix, need review

#176 Fix upload + Change upload error handling
  server/src/main/resources/messages.conf
  server/src/main/resources/messages.fr.conf
  server/src/main/scala/io/cumulus/controllers/FileSystemController.scala
  server/src/main/scala/io/cumulus/persistence/services/FsNodeService.scala
  server/src/main/scala/io/cumulus/persistence/services/StorageService.scala
  server/src/main/scala/io/cumulus/stages/ThumbnailStage.scala
Labels: back, feature, fix, need review

#177 Add caching to route generation
  server/build.sbt
  server/project/RoutesCompilation.scala
Labels: back, enhancement, need review, tooling

#173 Upload error handling
  client/src/components/upload/UploadFile.css
  client/src/components/upload/UploadFile.tsx
  client/src/files/fileSystem/FileSystemEpics.ts
  client/src/files/upload/UploadEpics.ts
  client/src/files/upload/UploadReducer.ts
  client/src/inAppNotif/InAppNotifActions.ts
  client/src/models/ApiError.ts
  client/src/models/FileToUpload.ts
  client/src/services/Api.ts
Labels: bug, front

#178 Fix sharing store
  server/src/main/scala/io/cumulus/persistence/stores/SharingStore.scala
Labels: back, fix, need review

#179 Typesafe-actions
  client/package-lock.json
  client/package.json
  client/src/auth/AuthActions.ts
  client/src/auth/AuthEpics.ts
  client/src/auth/AuthReducer.ts
  client/src/auth/login/LoginContainer.tsx
  client/src/auth/signup/SignupContainer.tsx
  client/src/components/RightPanel.tsx
  client/src/files/fileSystem/FileSystemActions.ts
  client/src/files/fileSystem/FileSystemContainer.tsx
  client/src/files/fileSystem/FileSystemEpics.ts
  client/src/files/fileSystem/FileSystemReducer.ts
  client/src/files/fileSystem/PreviewContainer.tsx
  client/src/files/move/MoveActions.ts
  client/src/files/move/MoveEpics.ts
  client/src/files/move/MoveModal.tsx
  client/src/files/move/MoveReducer.ts
  client/src/files/newFolder/NewFolderActions.ts
  client/src/files/newFolder/NewFolderContainer.tsx
  client/src/files/newFolder/NewFolderEpics.ts
  client/src/files/newFolder/NewFolderReducer.ts
  client/src/files/rename/FsNodeName.tsx
  client/src/files/rename/RenameActions.ts
  client/src/files/rename/RenameEpics.ts
  client/src/files/rename/RenameReducer.ts
  client/src/files/search/SearchActions.ts
  client/src/files/search/SearchContainer.tsx
  client/src/files/search/SearchEpics.ts
  client/src/files/search/SearchReducer.ts
  client/src/files/upload/DropUploaderContainer.tsx
  client/src/files/upload/UploadActions.ts
  client/src/files/upload/UploadContainer.tsx
  client/src/files/upload/UploadEpics.ts
  client/src/files/upload/UploadReducer.ts
  client/src/inAppNotif/InAppNotifActions.ts
  client/src/inAppNotif/InAppNotifContainer.tsx
  client/src/inAppNotif/InAppNotifEpics.ts
  client/src/inAppNotif/InAppNotifReducer.ts
Labels: enhancement, front

#184 Private key per file
  server/src/main/resources/evolutions/default/1.sql
  server/src/main/resources/messages.conf
  server/src/main/resources/messages.fr.conf
  server/src/main/scala/io/cumulus/CumulusRecoveryServer.scala
  server/src/main/scala/io/cumulus/CumulusServer.scala
  server/src/main/scala/io/cumulus/controllers/FileSystemController.scala
  server/src/main/scala/io/cumulus/core/json/JsonFormat.scala
  server/src/main/scala/io/cumulus/core/stream/storage/StorageReferenceReader.scala
  server/src/main/scala/io/cumulus/core/stream/storage/StorageReferenceWriter.scala
  server/src/main/scala/io/cumulus/core/utils/Crypto.scala
  server/src/main/scala/io/cumulus/models/Sharing.scala
  server/src/main/scala/io/cumulus/models/User.scala
  server/src/main/scala/io/cumulus/models/fs/FsNode.scala
  server/src/main/scala/io/cumulus/persistence/services/SharingService.scala
  server/src/main/scala/io/cumulus/persistence/services/StorageService.scala
  server/src/main/scala/io/cumulus/persistence/storage/StorageReference.scala
  server/src/main/scala/io/cumulus/persistence/stores/FsNodeStore.scala
  server/src/main/scala/io/cumulus/persistence/stores/SharingStore.scala
  server/src/main/scala/io/cumulus/stages/ThumbnailStage.scala
Labels: back, enhancement, need review, refacto

#187 Load external config + Configuration writer
  server/.gitignore
  server/project/plugins.sbt
  server/src/main/scala/io/cumulus/CumulusServer.scala
  server/src/main/scala/io/cumulus/core/utils/ConfigurationWriter.scala
  server/src/main/scala/io/cumulus/persistence/storage/StorageEngine.scala
  server/src/main/scala/io/cumulus/stages/CipherStage.scala
  server/src/main/scala/io/cumulus/stages/CompressionStage.scala
  server/src/main/scala/io/cumulus/stages/MetadataStage.scala
  server/src/main/scala/io/cumulus/stages/ThumbnailStage.scala
Labels: back, config, enhancement, feature, need review

#186 update doc
  README.md
  client/README.md
  server/README.md
Labels: documentation, enhancement

#191 Fix crypto + Zero warning
  server/build.sbt
  server/project/Dependencies.scala
  server/src/main/resources/routes
  server/src/main/scala/io/cumulus/CumulusRecoveryServer.scala
  server/src/main/scala/io/cumulus/CumulusServer.scala
  server/src/main/scala/io/cumulus/CumulusWatchdog.scala
  server/src/main/scala/io/cumulus/controllers/Assets.scala
  server/src/main/scala/io/cumulus/controllers/HomeController.scala
  server/src/main/scala/io/cumulus/controllers/SharingPublicController.scala
  server/src/main/scala/io/cumulus/core/persistence/anorm/AnormPKOperations.scala
  server/src/main/scala/io/cumulus/core/stream/storage/StorageReferenceReader.scala
  server/src/main/scala/io/cumulus/core/stream/storage/StorageReferenceWriter.scala
  server/src/main/scala/io/cumulus/models/User.scala
  server/src/main/scala/io/cumulus/models/fs/FsNode.scala
  server/src/main/scala/io/cumulus/persistence/storage/StorageReference.scala
  server/src/main/scala/io/cumulus/persistence/stores/FsNodeStore.scala
  server/src/main/scala/io/cumulus/stages/ThumbnailStage.scala
Labels: back, enhancement, fix, need review
