Repository Cumulus-Cloud/cumulus, pull requests merged in 2018-02, with the labels that each got.

#85 Dependencies update
  server/app/io/cumulus/core/json/JsonFormat.scala
  server/app/io/cumulus/persistence/services/StorageService.scala
  server/build.sbt
  server/project/Dependencies.scala
  server/project/build.properties
  server/project/plugins.sbt
Labels: back, enhancement, need review

#82 Error logging on failure
  server/app/io/cumulus/core/stream/storage/StorageReferenceReader.scala
  server/app/io/cumulus/persistence/storage/LocalStorageEngine.scala
  server/app/io/cumulus/persistence/storage/StorageEngine.scala
Labels: back, enhancement, need review

#88 add adminer to devtool
  devtools/docker/docker-compose.yml
Labels: enhancement

#87 Move
  client/package-lock.json
  client/package.json
  client/src/auth/login/LoginContainer.tsx
  client/src/auth/login/LoginForm.tsx
  client/src/auth/signup/SignupContainer.tsx
  client/src/auth/signup/SignupForm.tsx
  client/src/components/FsMetadata.css
  client/src/components/FsMetadata.tsx
  client/src/components/FsNodeComponent.tsx
  client/src/components/FsNodeInfos.tsx
  client/src/components/RightPanel.tsx
  client/src/components/breadcrumb/Breadcrumb.tsx
  client/src/components/buttons/BaseButton.css
  client/src/components/buttons/BaseButton.tsx
  client/src/components/buttons/Button.tsx
  client/src/components/buttons/FlatButton.css
  client/src/components/buttons/GhostButton.css
  client/src/components/buttons/GhostButton.tsx
  client/src/components/buttons/LinkButton.css
  client/src/components/buttons/LinkButton.tsx
  client/src/components/modals/ModalActions.css
  client/src/components/modals/ModalContent.css
  client/src/components/modals/ModalHeader.css
  client/src/fileSystem/FileSystemActions.ts
  client/src/fileSystem/FileSystemContainer.tsx
  client/src/fileSystem/FileSystemReducer.ts
  client/src/icons/DeleteIcon.tsx
  client/src/icons/FileDownloadIcon.tsx
  client/src/icons/MoveIcon.tsx
  client/src/icons/ShareIcon.tsx
  client/src/move/MoveActions.ts
  client/src/move/MoveModal.css
  client/src/move/MoveModal.tsx
  client/src/move/MoveReducer.ts
  client/src/move/TargetDirectory.css
  client/src/move/TargetDirectory.tsx
  client/src/newFolder/NewFolderContainer.tsx
  client/src/newFolder/NewFolderModal.tsx
  client/src/services/Api.ts
  client/src/store.ts
  client/src/upload/UploadContainer.tsx
  server/conf/messages.conf
  server/conf/messages.fr.conf
Labels: front, need review

#91 Rename
  client/package-lock.json
  client/package.json
  client/src/auth/login/LoginForm.tsx
  client/src/auth/signup/SignupForm.tsx
  client/src/components/FsNodeComponent.css
  client/src/components/FsNodeComponent.tsx
  client/src/components/FsNodeInfos.tsx
  client/src/components/KeyDownAction.tsx
  client/src/components/LeftPanel.css
  client/src/components/LeftPanel.tsx
  client/src/components/buttons/BaseButton.tsx
  client/src/components/buttons/FlatButton.tsx
  client/src/components/buttons/GhostButton.tsx
  client/src/components/buttons/IconButton.css
  client/src/components/buttons/IconButton.tsx
  client/src/fileSystem/FileSystemActions.ts
  client/src/fileSystem/FileSystemContainer.tsx
  client/src/fileSystem/FileSystemReducer.ts
  client/src/icons/AddIcon.tsx
  client/src/icons/DoneIcon.tsx
  client/src/icons/EditIcon.tsx
  client/src/rename/FsNodeName.css
  client/src/rename/FsNodeName.tsx
  client/src/rename/RenameActions.ts
  client/src/rename/RenameReducer.ts
  client/src/services/Api.ts
  client/src/store.ts
  server/conf/messages.conf
  server/conf/messages.fr.conf
Labels: front, need review

#98 Fix missing condition for move operation
  server/app/io/cumulus/models/Path.scala
  server/app/io/cumulus/persistence/services/FsNodeService.scala
  server/conf/messages.conf
  server/conf/messages.fr.conf
Labels: back, bug, need review
