Repository Cumulus-Cloud/cumulus, pull requests merged in 2018-05, with the labels that each got.

#205 Upgrade react-redux 6
  client/package-lock.json
  client/package.json
  client/src/auth/login/LoginContainer.tsx
  client/src/auth/signup/SignupContainer.tsx
  client/src/components/RightPanel.tsx
  client/src/definitions.d.ts
  client/src/files/fileSystem/FileSystemContainer.tsx
  client/src/files/fileSystem/PreviewContainer.tsx
  client/src/files/move/MoveModal.tsx
  client/src/files/newFolder/NewFolderContainer.tsx
  client/src/files/rename/FsNodeName.tsx
  client/src/files/search/SearchContainer.tsx
  client/src/files/upload/DropUploaderContainer.tsx
  client/src/files/upload/UploadContainer.tsx
  client/src/inAppNotif/InAppNotifContainer.tsx
Labels: fix, front

#206 Upgrade rxjs to version 6
  client/package-lock.json
  client/package.json
  client/src/auth/AuthEpics.ts
  client/src/files/fileSystem/FileSystemEpics.ts
  client/src/files/move/MoveEpics.ts
  client/src/files/newFolder/NewFolderEpics.ts
  client/src/files/rename/RenameEpics.ts
  client/src/files/search/SearchEpics.ts
  client/src/files/upload/UploadEpics.ts
  client/src/inAppNotif/InAppNotifEpics.ts
  client/src/main.tsx
  client/src/services/Api.ts
Labels: enhancement, front

#211 upgrade typesafe-actions
  client/package-lock.json
  client/package.json
  client/src/actions.ts
  client/src/auth/AuthActions.ts
  client/src/auth/AuthEpics.ts
  client/src/auth/AuthReducer.ts
  client/src/auth/login/LoginContainer.tsx
  client/src/auth/signup/SignupContainer.tsx
  client/src/files/fileSystem/FileSystemActions.ts
  client/src/files/fileSystem/FileSystemContainer.tsx
  client/src/files/fileSystem/FileSystemEpics.ts
  client/src/files/fileSystem/FileSystemReducer.ts
  client/src/files/fileSystem/PreviewContainer.tsx
  client/src/files/move/MoveActions.ts
  client/src/files/move/MoveEpics.ts
  client/src/files/move/MoveModal.tsx
  client/src/files/move/MoveReducer.ts
  client/src/files/newFolder/NewFolderActions.ts
  client/src/files/newFolder/NewFolderContainer.tsx
  client/src/files/newFolder/NewFolderEpics.ts
  client/src/files/newFolder/NewFolderReducer.ts
  client/src/files/rename/FsNodeName.tsx
  client/src/files/rename/RenameActions.ts
  client/src/files/rename/RenameEpics.ts
  client/src/files/search/SearchActions.ts
  client/src/files/search/SearchContainer.tsx
  client/src/files/search/SearchEpics.ts
  client/src/files/upload/DropUploaderContainer.tsx
  client/src/files/upload/UploadActions.ts
  client/src/files/upload/UploadContainer.tsx
  client/src/files/upload/UploadEpics.ts
  client/src/inAppNotif/InAppNotifActions.ts
  client/src/inAppNotif/InAppNotifReducer.ts
  client/src/store.ts
Labels: fix, front

#215 User sessions
  server/cumulus-core/src/main/scala/io/cumulus/controllers/utils/UserAuthentication.scala
  server/cumulus-core/src/main/scala/io/cumulus/core/Settings.scala
  server/cumulus-core/src/main/scala/io/cumulus/core/controllers/utils/authentication/Authentication.scala
  server/cumulus-core/src/main/scala/io/cumulus/core/json/JsonFormat.scala
  server/cumulus-core/src/main/scala/io/cumulus/core/persistence/anorm/AnormRepository.scala
  server/cumulus-core/src/main/scala/io/cumulus/core/stream/storage/StorageReferenceReader.scala
  server/cumulus-core/src/main/scala/io/cumulus/core/stream/storage/StorageReferenceWriter.scala
  server/cumulus-core/src/main/scala/io/cumulus/models/fs/FsNode.scala
  server/cumulus-core/src/main/scala/io/cumulus/models/user/Session.scala
  server/cumulus-core/src/main/scala/io/cumulus/models/user/User.scala
  server/cumulus-core/src/main/scala/io/cumulus/models/user/session/AuthenticationToken.scala
  server/cumulus-core/src/main/scala/io/cumulus/models/user/session/Session.scala
  server/cumulus-core/src/main/scala/io/cumulus/models/user/session/SessionInformation.scala
  server/cumulus-core/src/main/scala/io/cumulus/models/user/session/SharingSession.scala
  server/cumulus-core/src/main/scala/io/cumulus/models/user/session/UserSession.scala
  server/cumulus-core/src/main/scala/io/cumulus/persistence/stores/SessionStore.scala
  server/cumulus-core/src/main/scala/io/cumulus/persistence/stores/SharingStore.scala
  server/cumulus-core/src/main/scala/io/cumulus/persistence/stores/UserStore.scala
  server/cumulus-core/src/main/scala/io/cumulus/persistence/stores/filters/FsNodeFilter.scala
  server/cumulus-core/src/main/scala/io/cumulus/persistence/stores/filters/SessionFilter.scala
  server/cumulus-core/src/main/scala/io/cumulus/persistence/stores/orderings/FsNodeOrdering.scala
  server/cumulus-core/src/main/scala/io/cumulus/persistence/stores/orderings/SessionOrdering.scala
  server/cumulus-core/src/main/scala/io/cumulus/services/SessionService.scala
  server/cumulus-core/src/main/scala/io/cumulus/services/SharingService.scala
  server/cumulus-core/src/main/scala/io/cumulus/services/StorageService.scala
  server/cumulus-core/src/main/scala/io/cumulus/services/UserService.scala
  server/cumulus-core/src/main/scala/io/cumulus/stages/MetadataStage.scala
  server/cumulus-core/src/main/scala/io/cumulus/stages/ThumbnailStage.scala
  server/cumulus-main-module/src/main/resources/evolutions/default/1.sql
  server/cumulus-main-module/src/main/resources/routes
  server/cumulus-main-module/src/main/scala/io/cumulus/CumulusComponents.scala
  server/cumulus-main-module/src/main/scala/io/cumulus/controllers/FileSystemController.scala
  server/cumulus-main-module/src/main/scala/io/cumulus/controllers/HomeController.scala
  server/cumulus-main-module/src/main/scala/io/cumulus/controllers/ManagementController.scala
  server/cumulus-main-module/src/main/scala/io/cumulus/controllers/SharingController.scala
  server/cumulus-main-module/src/main/scala/io/cumulus/controllers/SharingPublicController.scala
  server/cumulus-main-module/src/main/scala/io/cumulus/controllers/UserController.scala
  server/cumulus-server-resources/src/main/resources/application.conf
  server/cumulus-server-resources/src/main/resources/messages.conf
Labels: back, enhancement, feature, need review
