Repository Cumulus-Cloud/cumulus, pull requests merged in 2018-03, with the labels that each got.

#104 In app notif
  client/package-lock.json
  client/package.json
  client/src/RootEpic.ts
  client/src/auth/AuthLayout.tsx
  client/src/auth/login/LoginActions.tsx
  client/src/auth/login/LoginEpics.ts
  client/src/auth/signup/SignupActions.tsx
  client/src/auth/signup/SignupEpics.ts
  client/src/fileSystem/FileSystemActions.ts
  client/src/fileSystem/FileSystemContainer.tsx
  client/src/fileSystem/FileSystemEpics.ts
  client/src/inAppNotif/InAppNotif.ts
  client/src/inAppNotif/InAppNotifActions.ts
  client/src/inAppNotif/InAppNotifContainer.css
  client/src/inAppNotif/InAppNotifContainer.tsx
  client/src/inAppNotif/InAppNotifEpics.ts
  client/src/inAppNotif/InAppNotifReducer.ts
  client/src/inAppNotif/InAppNotifService.ts
  client/src/main.tsx
  client/src/move/MoveActions.ts
  client/src/move/MoveEpics.ts
  client/src/newFolder/NewFolderActions.ts
  client/src/newFolder/NewFolderEpics.ts
  client/src/rename/FsNodeName.tsx
  client/src/rename/RenameActions.ts
  client/src/rename/RenameEpics.ts
  client/src/search/SearchActions.ts
  client/src/search/SearchEpics.ts
  client/src/store.ts
  client/src/upload/UploadActions.ts
  client/src/upload/UploadEpics.ts
  client/webpack.config.js
Labels: enhancement, front, need review

#105 Directory sharing update
  server/app/CumulusLoader.scala
  server/app/io/cumulus/controllers/FileSystemController.scala
  server/app/io/cumulus/controllers/SharingController.scala
  server/app/io/cumulus/controllers/payloads/fs/FsOperation.scala
  server/app/io/cumulus/controllers/payloads/fs/FsOperationType.scala
  server/app/io/cumulus/models/Path.scala
  server/app/io/cumulus/persistence/services/FsNodeService.scala
  server/app/io/cumulus/persistence/services/SharingService.scala
  server/app/io/cumulus/persistence/stores/SharingStore.scala
  server/conf/messages.conf
  server/conf/messages.fr.conf
  server/conf/routes
Labels: back, enhancement, need review

#106 Refactor project files
  client/src/RootEpic.ts
  client/src/components/AppBar.tsx
  client/src/components/FsNodeComponent.tsx
  client/src/components/RightPanel.tsx
  client/src/files/fileSystem/FileSystemActions.ts
  client/src/files/fileSystem/FileSystemContainer.css
  client/src/files/fileSystem/FileSystemContainer.tsx
  client/src/files/fileSystem/FileSystemEpics.ts
  client/src/files/fileSystem/FileSystemReducer.ts
  client/src/files/fileSystem/PreviewContainer.css
  client/src/files/fileSystem/PreviewContainer.tsx
  client/src/files/move/MoveActions.ts
  client/src/files/move/MoveEpics.ts
  client/src/files/move/MoveModal.css
  client/src/files/move/MoveModal.tsx
  client/src/files/move/MoveReducer.ts
  client/src/files/move/TargetDirectory.css
  client/src/files/move/TargetDirectory.tsx
  client/src/files/newFolder/NewFolderActions.ts
  client/src/files/newFolder/NewFolderContainer.tsx
  client/src/files/newFolder/NewFolderEpics.ts
  client/src/files/newFolder/NewFolderFrom.css
  client/src/files/newFolder/NewFolderFrom.tsx
  client/src/files/newFolder/NewFolderModal.tsx
  client/src/files/newFolder/NewFolderReducer.ts
  client/src/files/rename/FsNodeName.css
  client/src/files/rename/FsNodeName.tsx
  client/src/files/rename/RenameActions.ts
  client/src/files/rename/RenameEpics.ts
  client/src/files/rename/RenameReducer.ts
  client/src/files/search/SearchActions.ts
  client/src/files/search/SearchContainer.tsx
  client/src/files/search/SearchEpics.ts
  client/src/files/search/SearchReducer.ts
  client/src/files/upload/UploadActions.ts
  client/src/files/upload/UploadContainer.tsx
  client/src/files/upload/UploadEpics.ts
  client/src/files/upload/UploadReducer.ts
  client/src/inAppNotif/InAppNotifContainer.tsx
  client/src/main.tsx
  client/src/store.ts
Labels: front, refacto

#107 Fix weird JSON reader/writer error
  server/app/io/cumulus/models/fs/FsNode.scala
Labels: back, bug, need review

#111 Strip \u0000 from metadata
  server/app/io/cumulus/stages/MetadataStage.scala
Labels: back, fix

#108 Login refacto
  server/app/io/cumulus/controllers/UserController.scala
  server/app/io/cumulus/models/User.scala
  server/app/io/cumulus/models/fs/FsNode.scala
Labels: back, refacto

#112 Fix sharing download
  server/app/io/cumulus/controllers/FileSystemController.scala
  server/app/io/cumulus/controllers/SharingController.scala
  server/app/io/cumulus/persistence/services/StorageService.scala
Labels: back, fix, need review

#113 Add authentication from header
  server/app/io/cumulus/core/controllers/utils/authentication/Authentication.scala
Labels: back, enhancement, need review

#118 Use custom thread pool for database
  server/app/CumulusLoader.scala
  server/app/io/cumulus/core/persistence/query/QueryBuilder.scala
  server/conf/application.conf
Labels: back, enhancement, need review

#119 Handle multiple storage engines
  server/app/CumulusLoader.scala
  server/app/io/cumulus/core/Settings.scala
  server/app/io/cumulus/core/stream/storage/StorageObjectWriter.scala
  server/app/io/cumulus/core/stream/storage/StorageReferenceReader.scala
  server/app/io/cumulus/persistence/services/StorageService.scala
  server/app/io/cumulus/persistence/storage/LocalStorageEngine.scala
  server/app/io/cumulus/persistence/storage/StorageEngine.scala
  server/app/io/cumulus/persistence/storage/StorageObject.scala
  server/app/io/cumulus/persistence/storage/engines/LocalStorageEngine.scala
  server/app/io/cumulus/stages/CipherStage.scala
  server/app/io/cumulus/stages/CompressionStage.scala
  server/app/io/cumulus/stages/MetadataStage.scala
  server/app/io/cumulus/stages/ThumbnailStage.scala
  server/conf/application.conf
  server/conf/messages.conf
  server/conf/messages.fr.conf
Labels: back, enhancement, need review, refacto

#120 Fix error JSON for multiple errors for the same path
  server/app/io/cumulus/core/controllers/utils/api/ApiUtils.scala
Labels: back, bug, need review

#109 Refactor actions
  client/src/auth/AuthLayout.tsx
  client/src/auth/login/LoginActions.tsx
  client/src/auth/login/LoginContainer.tsx
  client/src/auth/login/LoginEpics.ts
  client/src/auth/login/LoginReducer.tsx
  client/src/auth/signup/SignupActions.tsx
  client/src/auth/signup/SignupContainer.tsx
  client/src/auth/signup/SignupEpics.ts
  client/src/auth/signup/SignupReducer.tsx
  client/src/components/FsNodeComponent.tsx
  client/src/files/fileSystem/FileSystemActions.ts
  client/src/files/fileSystem/FileSystemContainer.tsx
  client/src/files/fileSystem/FileSystemEpics.ts
  client/src/files/fileSystem/FileSystemReducer.ts
  client/src/files/move/MoveActions.ts
  client/src/files/move/MoveEpics.ts
  client/src/files/move/MoveModal.tsx
  client/src/files/newFolder/NewFolderActions.ts
  client/src/files/newFolder/NewFolderContainer.tsx
  client/src/files/newFolder/NewFolderEpics.ts
  client/src/files/newFolder/NewFolderReducer.ts
  client/src/files/rename/RenameActions.ts
  client/src/files/rename/RenameEpics.ts
  client/src/files/search/SearchActions.ts
  client/src/files/search/SearchEpics.ts
  client/src/files/upload/UploadActions.ts
  client/src/files/upload/UploadContainer.tsx
  client/src/files/upload/UploadEpics.ts
  client/src/files/upload/UploadReducer.ts
  client/src/inAppNotif/InAppNotifActions.ts
  client/src/inAppNotif/InAppNotifContainer.css
  client/src/inAppNotif/InAppNotifContainer.tsx
  client/src/services/Api.ts
Labels: WIP, refacto

#122 Better doc
  server/.gitignore
  server/README.md
  server/app/io/cumulus/core/Logging.scala
  server/app/io/cumulus/core/Settings.scala
  server/app/io/cumulus/core/controllers/utils/authentication/Authentication.scala
  server/app/io/cumulus/core/controllers/utils/bodyParser/BodyParserJson.scala
  server/app/io/cumulus/core/controllers/utils/bodyParser/BodyParserStream.scala
  server/app/io/cumulus/core/json/JsonFormat.scala
  server/app/io/cumulus/core/stream/storage/StorageObjectReader.scala
  server/app/io/cumulus/core/stream/storage/StorageObjectWriter.scala
  server/app/io/cumulus/core/stream/storage/StorageReferenceReader.scala
  server/app/io/cumulus/core/stream/storage/StorageReferenceWriter.scala
  server/app/io/cumulus/core/stream/utils/ByteRange.scala
  server/app/io/cumulus/core/stream/utils/Chunker.scala
  server/app/io/cumulus/core/stream/utils/Cipher.scala
  server/app/io/cumulus/core/stream/utils/DigestCalculator.scala
  server/app/io/cumulus/core/utils/Base64.scala
  server/app/io/cumulus/core/utils/Crypto.scala
  server/app/io/cumulus/core/utils/MimeType.scala
  server/app/io/cumulus/core/utils/Range.scala
  server/app/io/cumulus/core/validation/AppError.scala
  server/app/io/cumulus/core/validation/AppErrorType.scala
  server/app/io/cumulus/persistence/services/StorageService.scala
  server/app/io/cumulus/persistence/storage/StorageEngine.scala
  server/app/io/cumulus/persistence/storage/StorageReference.scala
  server/app/io/cumulus/persistence/storage/engines/LocalStorageEngine.scala
  server/app/io/cumulus/persistence/stores/FsNodeFilter.scala
  server/app/io/cumulus/persistence/stores/FsNodeStore.scala
  server/app/io/cumulus/persistence/stores/SharingStore.scala
  server/app/io/cumulus/persistence/stores/UserStore.scala
  server/app/io/cumulus/stages/CipherStage.scala
  server/app/io/cumulus/stages/CompressionStage.scala
  server/app/io/cumulus/stages/MetadataStage.scala
  server/app/io/cumulus/stages/ThumbnailStage.scala
  server/conf/application.conf
  server/conf/local.example.conf
Labels: back, documentation, need review
